require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ContentBlocksController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::ContentBlock. As you add validations to Admin::ContentBlock, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ContentBlocksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_content_blocks as @admin_content_blocks" do
      content_block = Admin::ContentBlock.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_content_blocks).should eq([content_block])
    end
  end

  describe "GET show" do
    it "assigns the requested content_block as @content_block" do
      content_block = Admin::ContentBlock.create! valid_attributes
      get :show, {:id => content_block.to_param}, valid_session
      assigns(:content_block).should eq(content_block)
    end
  end

  describe "GET new" do
    it "assigns a new content_block as @content_block" do
      get :new, {}, valid_session
      assigns(:content_block).should be_a_new(Admin::ContentBlock)
    end
  end

  describe "GET edit" do
    it "assigns the requested content_block as @content_block" do
      content_block = Admin::ContentBlock.create! valid_attributes
      get :edit, {:id => content_block.to_param}, valid_session
      assigns(:content_block).should eq(content_block)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::ContentBlock" do
        expect {
          post :create, {:content_block => valid_attributes}, valid_session
        }.to change(Admin::ContentBlock, :count).by(1)
      end

      it "assigns a newly created content_block as @content_block" do
        post :create, {:content_block => valid_attributes}, valid_session
        assigns(:content_block).should be_a(Admin::ContentBlock)
        assigns(:content_block).should be_persisted
      end

      it "redirects to the created content_block" do
        post :create, {:content_block => valid_attributes}, valid_session
        response.should redirect_to(Admin::ContentBlock.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved content_block as @content_block" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ContentBlock.any_instance.stub(:save).and_return(false)
        post :create, {:content_block => {}}, valid_session
        assigns(:content_block).should be_a_new(Admin::ContentBlock)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ContentBlock.any_instance.stub(:save).and_return(false)
        post :create, {:content_block => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested content_block" do
        content_block = Admin::ContentBlock.create! valid_attributes
        # Assuming there are no other admin_content_blocks in the database, this
        # specifies that the Admin::ContentBlock created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::ContentBlock.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => content_block.to_param, :content_block => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested content_block as @content_block" do
        content_block = Admin::ContentBlock.create! valid_attributes
        put :update, {:id => content_block.to_param, :content_block => valid_attributes}, valid_session
        assigns(:content_block).should eq(content_block)
      end

      it "redirects to the content_block" do
        content_block = Admin::ContentBlock.create! valid_attributes
        put :update, {:id => content_block.to_param, :content_block => valid_attributes}, valid_session
        response.should redirect_to(content_block)
      end
    end

    describe "with invalid params" do
      it "assigns the content_block as @content_block" do
        content_block = Admin::ContentBlock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ContentBlock.any_instance.stub(:save).and_return(false)
        put :update, {:id => content_block.to_param, :content_block => {}}, valid_session
        assigns(:content_block).should eq(content_block)
      end

      it "re-renders the 'edit' template" do
        content_block = Admin::ContentBlock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::ContentBlock.any_instance.stub(:save).and_return(false)
        put :update, {:id => content_block.to_param, :content_block => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested content_block" do
      content_block = Admin::ContentBlock.create! valid_attributes
      expect {
        delete :destroy, {:id => content_block.to_param}, valid_session
      }.to change(Admin::ContentBlock, :count).by(-1)
    end

    it "redirects to the admin_content_blocks list" do
      content_block = Admin::ContentBlock.create! valid_attributes
      delete :destroy, {:id => content_block.to_param}, valid_session
      response.should redirect_to(admin_content_blocks_url)
    end
  end

end
